### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/ACRO#149]
The CI tools (including the tests) are run using the dependency versions from `requirements.txt` so the pandas version we test against is 1.4.4. However, when running the tests with the latest pandas, the error below is generated. As a temporary solution, the `setup.py` version has been set to `~=1.4.4`. We should either figure out how to change our code to be compatible with 2.1.0 or find out what the maximum version number is that acro works with to set the version number more loosely i.e., `<=`.

The error with `pandas==2.1.0`:
```
data =        charity grant_type  index  year  inc_activity  inc_grants  ...  sh_assets_balance  sh_income_assets  sh_staff_a...0.391120          0.203788         3.242479               0.062849               0.308406  4.0

[918 rows x 44 columns]
acro = <acro.acro.ACRO object at 0x7fc3449b3340>

    def test_finalise_json(data, acro):
        """Finalise json test."""
        _ = acro.crosstab(data.year, data.grant_type)
        acro.add_exception("output_0", "Let me have it")
        # write JSON
        result: Records = acro.finalise(PATH, "json")
        # load JSON
        loaded: Records = load_records(PATH)
        orig = result.get_index(0)
        read = loaded.get_index(0)
        print("*****************************")
        print(orig)
        print("*****************************")
        print(read)
        print("*****************************")
        # check equal
        assert orig.uid == read.uid
        assert orig.status == read.status
        assert orig.output_type == read.output_type
        assert orig.properties == read.properties
        assert orig.sdc == read.sdc
        assert orig.command == read.command
        assert orig.summary == read.summary
        assert orig.comments == read.comments
        assert orig.timestamp == read.timestamp
>       assert (orig.output[0].reset_index()).equals(read.output[0])
E       assert False
E        +  where False = <bound method NDFrame.equals of grant_type  year   G   N   R  R/G\n0           2010  15  59  71  NaN\n1           2011  ... 15  59  71  NaN\n3           2013  15  59  71  NaN\n4           2014  15  59  71  NaN\n5           2015  15  59  71  NaN>(   year   G   N   R  R/G\n0  2010  15  59  71  NaN\n1  2011  15  59  71  NaN\n2  2012  15  59  71  NaN\n3  2013  15  59  71  NaN\n4  2014  15  59  71  NaN\n5  2015  15  59  71  NaN)
E        +    where <bound method NDFrame.equals of grant_type  year   G   N   R  R/G\n0           2010  15  59  71  NaN\n1           2011  ... 15  59  71  NaN\n3           2013  15  59  71  NaN\n4           2014  15  59  71  NaN\n5           2015  15  59  71  NaN> = grant_type  year   G   N   R  R/G\n0           2010  15  59  71  NaN\n1           2011  15  59  71  NaN\n2           2012  15  59  71  NaN\n3           2013  15  59  71  NaN\n4           2014  15  59  71  NaN\n5           2015  15  59  71  NaN.equals
E        +      where grant_type  year   G   N   R  R/G\n0           2010  15  59  71  NaN\n1           2011  15  59  71  NaN\n2           2012  15  59  71  NaN\n3           2013  15  59  71  NaN\n4           2014  15  59  71  NaN\n5           2015  15  59  71  NaN = <bound method DataFrame.reset_index of grant_type   G   N   R  R/G\nyear                       \n2010        15  59  71 ...1  NaN\n2012        15  59  71  NaN\n2013        15  59  71  NaN\n2014        15  59  71  NaN\n2015        15  59  71  NaN>()
E        +        where <bound method DataFrame.reset_index of grant_type   G   N   R  R/G\nyear                       \n2010        15  59  71 ...1  NaN\n2012        15  59  71  NaN\n2013        15  59  71  NaN\n2014        15  59  71  NaN\n2015        15  59  71  NaN> = grant_type   G   N   R  R/G\nyear                       \n2010        15  59  71  NaN\n2011        15  59  71  NaN\n2012        15  59  71  NaN\n2013        15  59  71  NaN\n2014        15  59  71  NaN\n2015        15  59  71  NaN.reset_index

test/test_initial.py:318: AssertionError
```

**Comment by rpreen** [comment]
I have added CI tests for Python versions 3.8, 3.9, 3.10, and 3.11 in #150 

Also, I have updated the pandas version to 1.5.0 because this has wheels available for all of the above mentioned Python versions and the tests all succeed, whereas with 1.4.4 there is no wheel available for pandas 1.4.4.

**Comment by rpreen** [comment]
It should also be noted that aisdc currently uses scikit-learn version 1.1.3 and some of the tests seem to depend on this version and fail with newer versions.

**Comment by jim-smith** [comment]
Putting this on hold for now because it is all affected by what dependencies aisdc inherits from tensorflow-privacy

**Comment by rpreen** [comment]
The assertion above passes with Pandas 1.5.3, but fails with Pandas >2 because they have made the [`equals()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html) function more strict so that it also checks the DataFrame metadata (index names and dtypes, etc.) are equal. Since we're only using this to serialise the SDC outcome DataFrames, we only care that that contents are reloaded correctly. There is an [`assert_frame_equal()`](https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html) function which can perform the equality check but optionally ignore the metadata.

So changing the test assertion as follows should fix the error:

From:

```python
    assert (orig.output[0].reset_index()).equals(read.output[0])
```

To:

```python
    orig_df = orig.output[0].reset_index()
    read_df = read.output[0]
    pd.testing.assert_frame_equal(
        orig_df, read_df, check_names=False, check_dtype=False
    ) 
```

**Comment by rpreen** [comment]
There is one other test that fails with Pandas >2, which is `test_crosstab_with_totals_and_empty_data()` and is due to changes in the `crosstab()` function where in 1.5.3 it raises a [value error](https://github.com/pandas-dev/pandas/blob/v1.5.3/pandas/core/reshape/pivot.py#L543-L710) if the DataFrame is empty and the ACRO code relies on this to throw an exception, however in Pandas >2 there is more robust error handling and instead of raising an error it simply returns an empty DataFrame.

Adding the following before calling `crosstab()` in the `crosstab_with_totals()` function in `acro_tables.py` seems to solve all of the test issues in both 1.5.3 and 2.2.3

```python
            if table.empty:
                raise ValueError("empty table") 
```
