### ISSUE TITLE
digitally sign acro outputs

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/ACRO#38]
very much a 'simple thing that could be done if TREs are worried that some users might edit acro outputs after we have checked them and said they are ok.

Won't in the MOSCoW category for SACRO

**Comment by jim-smith** [comment]
At DAREUK mid-projects meeting. 
We should add this asap to because people running TREs trust researchers less than we might think. Takes us to similar levels of security to aisdc.

shar512 checksum seems to be preferred method for TRE-FX

**Comment by jim-smith** [comment]
@rpreen This has become more urgent since we removed the timestamp from the filenames - which some TRE staff had said they particularly liked during evaluation.
Can we add timestamp as a field?

**Comment by rpreen** [comment]
The timestamp is still there as a field.

**Comment by jim-smith** [comment]
Cool.
I wonder if we should ask @benbc whether they could flag in their code that the file had been changed since the timestamp?

**Comment by benbc** [comment]
What are we trying to guard against here? It seems difficult to stop researchers from deliberately modifying the output post-check. They could always change the JSON timestamp too. (And update any checksum we include.)

**Comment by jim-smith** [comment]
Inadvertent bad practice/ mistakes.    
Quite agree that we can't possibly be secure against everything.
