### ISSUE TITLE
Providing additional information in ACRO outputs

### ISSUE THREAD

**Issue by rpreen** [AI-SDC/ACRO#72]
In addition to providing automated rules-based checking, should ACRO include/highlight further information for the checker (such as for which there may not be any rules)? For example, in [this handbook](https://ukdataservice.ac.uk/app/uploads/thf_datareport_aw_web.pdf), the regressions section include a "minimum requirement" and that includes: Number of observations, Degrees of freedom, Variable labels, Omitted parameters, Cohort specification. 

The ACRO output for regressions currently includes the degrees of freedom in the summary because that's what it checks. But we could easily include in the summary something like "additional information: variable labels = ["bla", "blah"]. Ideally we would automatically extract as much of this information as possible, but we could also just provide a prompt to the user asking them to supply it after they run an `acro.ols()`? 

For situations where we don't have/know an appropriate rule but we do know the variables/requirements that matter, if we structured that information in the JSON output (e.g., "dof": 5) and then subsequently the result of the TRE checker was also recorded in a structured way, this might enable the rules to be learnt. In this example, if we knew that dof was important but didn't know that TRE checkers deem a value above/below 10 to be important, we could learn that information?

**Comment by rpreen** [comment]
Somewhat related to this is dealing with matplotlib figures. Currently, we have a function to add a custom output, which would mean that the researcher generates their plot as a png/pdf/etc. and then adds the path to the file, along with a text note describing the figure. It would be useful to get things like the type of the plot, the title, and the label names, etc. into a structured format (rather than the free text of a comment) -- even if we can't apply automated rules.

One option could be to include a more specific function that allows the researcher to add metadata as a dictionary - and if we had requirements for certain outputs we could then warn/require the researcher to complete all of the information (e.g., researcher specifies the plot is a linear regression, so then they must specify some other property like the degrees of freedom).

Better still would be to automatically extract some of the properties if we had a function that received a matplotlib figure then it could possibly pull out the labels and type etc. and then the researcher could add the missing requirements?

So each output should have a dictionary entry that includes as much structured information as possible.

What we have now is:

```json
{
	"name_timestamp": {
		"command": "",
		"summary": "",
		"outcome": "",
		"output": "",
		"timestamp": "",
		"comments": ""
	}
}
```

And for a regression an example entry would be `"summary": "pass; dof=806.0 >= 10"`.  Making this structured could look something like adding a `properties` dictionary (and a `type` entry).

```json
{
	"name_timestamp": {
		"command": "",
		"summary": "",
		"outcome": "",
		"output": "",
                "type": "regression",
		"properties": {
                        "method": "least squares",
			"dof": 806,
                        "x-labels": ["inc_grants", "inc_donations", "total_costs", "constant"],
                        "y-labels": ["inc_activity"]
		}
		"timestamp": "",
		"comments": ""
	}
}
```

**Comment by jim-smith** [comment]
@rpreen I see where you are getting at. This needs discussing together with the aisdc team and the GUI team so the latter know what to expect.
I have some code that interrogates matplotlib fig and ax objects, and can extract title and axis labels from most things, but there are many ways of generating them ...

**Comment by bloodearnest** [comment]
Looks great, this would be useful for us in the GUI team.

Specifically:

* explicit output `type` field (rather than having to guess by parsing `command` string currently)
* structured summary/properties (rather than having to parse `summary` string)

**Comment by bloodearnest** [comment]
A related extra of structured: could we have an explicit boolean `status` (or similar) field for indicated high level pass/fail status for an output?

Currently, we have to check if `summary` string starts with `"pass"` or `"fail"`.

**Comment by rpreen** [comment]
Yeah, adding a `status` field makes sense.
