### ISSUE TITLE
In JSON output, outcomes are encoded as embedded strings, rather than as JSON objects

### ISSUE THREAD

**Issue by bloodearnest** [AI-SDC/ACRO#73]
Hi there from your friends over at OpenSAFELY

When getting familiar and testing out ACRO, we noticed the `outcome` field is encoded as a string representing a JSON object, as opposed to just a JSON object like we would have expected. e.g.

```{
    {
    "output_0_2023-05-17-15422890": {
        "command": "safe_table = acro.crosstab(df.recommend, df.parents)",
        "summary": "fail; threshold: 4 cells suppressed; ",
        "outcome": "{\"great_pret\":{\"not_recom\":\"ok\",\"priority\":\"ok\",\"recommend\":\"threshold; \",\"spec_prior\":\"ok\",\"very_recom\":\"threshold; \"},\"pretentious\":{\"not_recom\":\"ok\",\"priority\":\"ok\",\"recommend\":\"threshold; \",\"spec_prior\":\"ok\",\"very_recom\":\"ok\"},\"usual\":{\"not_recom\":\"ok\",\"priority\":\"ok\",\"recommend\":\"threshold; \",\"spec_prior\":\"ok\",\"very_recom\":\"ok\"}}",
        "output": "/home/wavy/bennett/test-oxcef/outputs/output_0_2023-05-17-15422890.csv",
        "timestamp": "2023-05-17-15422890",
        "comments": "Please let me have this data., 6 cells were supressed in this table"
    }
}
```

This means that to inspect the JSON outcome field programatically, we need to do something like:

```
outcome = json.loads(data["output_0_2023-05-17-15422890"]["outcome"])
```

Is this intended behaviour?

If not, I'd be happy to create a PR to fix, with tests.

**Comment by jim-smith** [comment]
@bloodearnest good spot. Will check with Richard and Maha whether there is a particular reason we did it like this.

@rpreen @mahaalbashir ?

**Comment by rpreen** [comment]
I don't think there was an intentional design decision around making it a string. It looks to me like we just call the Pandas [`to_json()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html) function which converts the DataFrame to a str JSON:

https://github.com/AI-SDC/ACRO/blob/693ab0ea70f6aa4bf81674c8f465484e0d64a112/acro/utils.py#L81-L84

Just be careful with the reloading that we do already, which I thought was tested so presumably that works ok:

https://github.com/AI-SDC/ACRO/blob/693ab0ea70f6aa4bf81674c8f465484e0d64a112/acro/utils.py#L99-L106

**Comment by bloodearnest** [comment]
We would definitely want this, tbh

The json as is will of course load just fine - a string is a valid data type.

But if you try to use the detailed information in the `outcome` field (as we are), you have to manually parse each outcome field from a string to json. There doesn't seem to be any reason to serialize it as a string from the above discussion, so can we request it is serialized as a dict instead?

Happy to create a PR for it if so.

**Comment by rpreen** [comment]
Makes sense; happy to merge if you create a PR.

**Comment by jim-smith** [comment]
@bloodearnest are you happy for me to assign this to the sprint due for delivery on July 14th?

**Comment by bloodearnest** [comment]
> @bloodearnest are you happy for me to assign this to the sprint due for delivery on July 14th?

Yes, I'm working on a PR currently :+1:
