### ISSUE TITLE
write to excel fails if output is not a table

### ISSUE THREAD

**Issue by jim-smith** [AI-SDC/ACRO#78]
# error message
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[26], line 1
----> 1 output = acro.finalise("test_results.xlsx")

File ~/GitHub/AI-SDC/ACRO/acro/acro.py:86, in ACRO.finalise(self, filename)
     84     utils.finalise_json(filename, self.results)
     85 elif extension == ".xlsx":
---> 86     utils.finalise_excel(filename, self.results)
     87 else:
     88     raise ValueError("Invalid file extension. Options: {.json, .xlsx}")

File ~/GitHub/AI-SDC/ACRO/acro/utils.py:147, in finalise_excel(filename, results)
    145 for table in output["output"]:
    146     start = 1 + writer.sheets[output_id].max_row
--> 147     table.to_excel(writer, sheet_name=output_id, startrow=start)

AttributeError: 'str' object has no attribute 'to_excel'

### to reproduce
 run test.ipynb (the one that uses the charity data)
and add a cell at the end with the command
output = acro.finalise("test_results.xlsx")

### cause
in utils.py around line 147
            for table in output["output"]:
                start = 1 + writer.sheets[output_id].max_row
                table.to_excel(writer, sheet_name=output_id, startrow=start)

### Fix
Assumption is that the output is a table, which is not always true (e.g. unsupported output)
need to test the type and the write out as appropriate if it is jsut a string

**Comment by rpreen** [comment]
Do we actually want to keep supporting xlsx outputs from within acro?

It seemed like at the previous meeting people wanted acro to **not** automatically apply suppression. That instead, it would be preferable if the suppression masks were passed (along with the unredacted output) to the TRE tool wherein the checker would indicate which outputs could be released without suppression (if there was a valid exception) or to apply the suppression at that point. Moreover, the JSON output is what will be read by the TRE tool, so if acro produces both JSON and another file format (such as xlsx) there is a difference between the format the TRE checker is inspecting and the format taken by the researcher. The TRE tool would therefore seem the best place to do the format conversion to something like xlsx if the researcher requests that output type?

**Comment by jim-smith** [comment]
agree about not doing suppression automatically but rather passing masks to gui via the .json. WP3 team confident they can do better visualisation if we do that.

@rpreen Don't see why that impacts on us being able to provide .xlsx outputs for TREs that don't want / can't install the GUI tool.  At present it creates a sheet inside the workbook for each output that shows the (combined) masks and then underneath that the (currently suppressed) table.

Agree we should change the default behaviour to not suppressing, but don't think that affects this issue, which is just handling the case when output is the string  "unsupported item" rather than a pandas table
